name: ci

on:
  push:
    branches:
      - "main"

jobs:
  manylinux2014_x86_64:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push amd64
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          build-args: |
            ARCH=x86_64
            MANYLINUXIMG=manylinux2014
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/llvm_manylinux2014_x86_64:latest
  manylinux_2_28_x86_64:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push amd64
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          build-args: |
            ARCH=x86_64
            MANYLINUXIMG=manylinux_2_28
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/llvm_manylinux_2_28_x86_64:latest
