name: ci

on:
  push:
    branches:
      - "main"

jobs:
  multi_arch_build:
    runs-on: ${{ matrix.arch_info.RUNNER }}

    strategy:
      matrix:
        arch_info:
          # Configuration for x86_64 (amd64).
          - PLATFORM: linux/amd64
            ARCH_ARG: x86_64
            TAG_SUFFIX: x86_64
            MANYLINUX_TAG: manylinux_2_28
            RUNNER: ubuntu-latest

          # Configuration for aarch64 (arm64).
          - PLATFORM: linux/arm64
            ARCH_ARG: aarch64
            TAG_SUFFIX: aarch64
            MANYLINUX_TAG: manylinux_2_28
            RUNNER: ubuntu-24.04-arm

    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push ${{ matrix.arch_info.PLATFORM }}
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          platforms: ${{ matrix.arch_info.PLATFORM }}
          push: true
          build-args: |
            ARCH=${{ matrix.arch_info.ARCH_ARG }}
            MANYLINUXIMG=${{ matrix.arch_info.MANYLINUX_TAG }}
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/llvm_${{ matrix.arch_info.MANYLINUX_TAG }}_${{ matrix.arch_info.TAG_SUFFIX }}:latest
